esquema_origen: SPE
tablas:
  DR$DEMANDA_TEXT_IDX$K:
    descripcion: Inventario tecnico de la tabla DR$DEMANDA_TEXT_IDX$K
    destino_sugerido: POSTGRESQL
    sensible: false
  DR$ONP_DESCRIPCION_TEXT_IDX$K:
    descripcion: Inventario tecnico de la tabla DR$ONP_DESCRIPCION_TEXT_IDX$K
    destino_sugerido: POSTGRESQL
    sensible: false
  AAA_CRUCE_FOSFEC_MARZO_2020:
    descripcion: Inventario tecnico de la tabla AAA_CRUCE_FOSFEC_MARZO_2020
    destino_sugerido: MONGODB
    sensible: false
  AC_ACCIONES_ORIENTACION:
    descripcion: Inventario tecnico de la tabla AC_ACCIONES_ORIENTACION
    destino_sugerido: MONGODB
    sensible: true
  AC_COLOCACIONES:
    descripcion: Inventario tecnico de la tabla AC_COLOCACIONES
    destino_sugerido: MONGODB
    sensible: true
  AC_INSCRITOS:
    descripcion: Inventario tecnico de la tabla AC_INSCRITOS
    destino_sugerido: MONGODB
    sensible: true
  AC_ORIENTADOS:
    descripcion: Inventario tecnico de la tabla AC_ORIENTADOS
    destino_sugerido: MONGODB
    sensible: true
  AC_POSTULACIONES:
    descripcion: Inventario tecnico de la tabla AC_POSTULACIONES
    destino_sugerido: MONGODB
    sensible: true
  ARREGLO_1:
    descripcion: Inventario tecnico de la tabla ARREGLO_1
    destino_sugerido: MONGODB
    sensible: false
  CAMBIOS_REGISTRO_ORO:
    descripcion: Inventario tecnico de la tabla CAMBIOS_REGISTRO_ORO
    destino_sugerido: POSTGRESQL
    sensible: true
  CIFRAS_COLOCACIONES:
    descripcion: Inventario tecnico de la tabla CIFRAS_COLOCACIONES
    destino_sugerido: MONGODB
    sensible: true
  CIFRAS_INSCRITOS:
    descripcion: Inventario tecnico de la tabla CIFRAS_INSCRITOS
    destino_sugerido: MONGODB
    sensible: true
  CIFRAS_ORIENTADOS:
    descripcion: Inventario tecnico de la tabla CIFRAS_ORIENTADOS
    destino_sugerido: MONGODB
    sensible: true
  CIFRAS_SOLICITUDES:
    descripcion: Inventario tecnico de la tabla CIFRAS_SOLICITUDES
    destino_sugerido: MONGODB
    sensible: true
  CMP3$93278:
    descripcion: Inventario tecnico de la tabla CMP3$93278
    destino_sugerido: MONGODB
    sensible: false
  CMP3$93887:
    descripcion: Inventario tecnico de la tabla CMP3$93887
    destino_sugerido: MONGODB
    sensible: false
  CONTROL_DEMANDA:
    descripcion: Inventario tecnico de la tabla CONTROL_DEMANDA
    destino_sugerido: POSTGRESQL
    sensible: false
  CONTROL_OFERTA:
    descripcion: Inventario tecnico de la tabla CONTROL_OFERTA
    destino_sugerido: POSTGRESQL
    sensible: false
  CORREO_OFT_EMP:
    descripcion: Inventario tecnico de la tabla CORREO_OFT_EMP
    destino_sugerido: POSTGRESQL
    sensible: false
  CRU_EVENTO_CAMBIO:
    descripcion: Inventario tecnico de la tabla CRU_EVENTO_CAMBIO
    destino_sugerido: POSTGRESQL
    sensible: false
  CRUCE_DPS:
    descripcion: Inventario tecnico de la tabla CRUCE_DPS
    destino_sugerido: MONGODB
    sensible: true
  CZ_OFERTA:
    descripcion: Inventario tecnico de la tabla CZ_OFERTA
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFT_ETD_FORM:
    descripcion: Inventario tecnico de la tabla CZ_OFT_ETD_FORM
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFT_ETD_NFORM:
    descripcion: Inventario tecnico de la tabla CZ_OFT_ETD_NFORM
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFT_EXP:
    descripcion: Inventario tecnico de la tabla CZ_OFT_EXP
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFT_EXP_IND:
    descripcion: Inventario tecnico de la tabla CZ_OFT_EXP_IND
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFT_IDIOMA:
    descripcion: Inventario tecnico de la tabla CZ_OFT_IDIOMA
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFT_LICENCIA:
    descripcion: Inventario tecnico de la tabla CZ_OFT_LICENCIA
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFT_VEHICULO:
    descripcion: Inventario tecnico de la tabla CZ_OFT_VEHICULO
    destino_sugerido: POSTGRESQL
    sensible: false
  CZ_OFTXPES:
    descripcion: Inventario tecnico de la tabla CZ_OFTXPES
    destino_sugerido: POSTGRESQL
    sensible: false
  DEM_ETD_FORMAL:
    descripcion: Inventario tecnico de la tabla DEM_ETD_FORMAL
    destino_sugerido: POSTGRESQL
    sensible: false
  DEM_VARIABLE_CRUCE:
    descripcion: Inventario tecnico de la tabla DEM_VARIABLE_CRUCE
    destino_sugerido: POSTGRESQL
    sensible: false
  DEMANDA:
    descripcion: Inventario tecnico de la tabla DEMANDA
    destino_sugerido: POSTGRESQL
    sensible: true
  DEMANDA_FUNCION_CPL:
    descripcion: Inventario tecnico de la tabla DEMANDA_FUNCION_CPL
    destino_sugerido: POSTGRESQL
    sensible: false
  DEMANDA_OCUPACION:
    descripcion: Inventario tecnico de la tabla DEMANDA_OCUPACION
    destino_sugerido: POSTGRESQL
    sensible: false
  DEMXFUNCION:
    descripcion: Inventario tecnico de la tabla DEMXFUNCION
    destino_sugerido: POSTGRESQL
    sensible: false
  DR$OEX_FUNCIONES_TEXT_IDX$I:
    descripcion: Inventario tecnico de la tabla DR$OEX_FUNCIONES_TEXT_IDX$I
    destino_sugerido: MONGODB
    sensible: false
  DR$OEX_FUNCIONES_TEXT_IDX$K:
    descripcion: Inventario tecnico de la tabla DR$OEX_FUNCIONES_TEXT_IDX$K
    destino_sugerido: POSTGRESQL
    sensible: false
  DR$OFERTA_CORREO_CTX$I:
    descripcion: Inventario tecnico de la tabla DR$OFERTA_CORREO_CTX$I
    destino_sugerido: MONGODB
    sensible: false
  DR$OFERTA_CORREO_CTX$K:
    descripcion: Inventario tecnico de la tabla DR$OFERTA_CORREO_CTX$K
    destino_sugerido: POSTGRESQL
    sensible: false
  DR$ONP_DESCRIPCION_TEXT_IDX$I:
    descripcion: Inventario tecnico de la tabla DR$ONP_DESCRIPCION_TEXT_IDX$I
    destino_sugerido: MONGODB
    sensible: false
  DWH_ORIE_FUN:
    descripcion: Inventario tecnico de la tabla DWH_ORIE_FUN
    destino_sugerido: MONGODB
    sensible: false
  DWH_ORIE_MUN:
    descripcion: Inventario tecnico de la tabla DWH_ORIE_MUN
    destino_sugerido: MONGODB
    sensible: true
  DWH_SEGU_FUN:
    descripcion: Inventario tecnico de la tabla DWH_SEGU_FUN
    destino_sugerido: MONGODB
    sensible: false
  DWH_SEGU_MUN:
    descripcion: Inventario tecnico de la tabla DWH_SEGU_MUN
    destino_sugerido: MONGODB
    sensible: true
  EGRESADO:
    descripcion: Inventario tecnico de la tabla EGRESADO
    destino_sugerido: MONGODB
    sensible: false
  EGRESADO_AUX:
    descripcion: Inventario tecnico de la tabla EGRESADO_AUX
    destino_sugerido: MONGODB
    sensible: false
  EGRESADO_SIMULA:
    descripcion: Inventario tecnico de la tabla EGRESADO_SIMULA
    destino_sugerido: MONGODB
    sensible: false
  ENVIO:
    descripcion: Inventario tecnico de la tabla ENVIO
    destino_sugerido: POSTGRESQL
    sensible: false
  EXPERIENCIAXFUNCION:
    descripcion: Inventario tecnico de la tabla EXPERIENCIAXFUNCION
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_ARI_DEM:
    descripcion: Inventario tecnico de la tabla HIS_ARI_DEM
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_BARRIO_OFT:
    descripcion: Inventario tecnico de la tabla HIS_BARRIO_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_DEMANDA_CNO:
    descripcion: Inventario tecnico de la tabla HIS_DEMANDA_CNO
    destino_sugerido: MONGODB
    sensible: false
  HIS_ESTADO_CIVIL_OFT:
    descripcion: Inventario tecnico de la tabla HIS_ESTADO_CIVIL_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_ESTADO_DEMANDA:
    descripcion: Inventario tecnico de la tabla HIS_ESTADO_DEMANDA
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_ESTADO_EMPRESA:
    descripcion: Inventario tecnico de la tabla HIS_ESTADO_EMPRESA
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_ESTADO_OFERTA:
    descripcion: Inventario tecnico de la tabla HIS_ESTADO_OFERTA
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_ESTRATO_OFT:
    descripcion: Inventario tecnico de la tabla HIS_ESTRATO_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_MUNICIPIO_OFT:
    descripcion: Inventario tecnico de la tabla HIS_MUNICIPIO_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_OCUP_PREFERENCIA:
    descripcion: Inventario tecnico de la tabla HIS_OCUP_PREFERENCIA
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_OFTXPES:
    descripcion: Inventario tecnico de la tabla HIS_OFTXPES
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_ORIENTACION_OFT:
    descripcion: Inventario tecnico de la tabla HIS_ORIENTACION_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_PER_CARGO_OFT:
    descripcion: Inventario tecnico de la tabla HIS_PER_CARGO_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_POS_FAM_OFT:
    descripcion: Inventario tecnico de la tabla HIS_POS_FAM_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_SEG_DEMANDA:
    descripcion: Inventario tecnico de la tabla HIS_SEG_DEMANDA
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_SEG_EMPRESA:
    descripcion: Inventario tecnico de la tabla HIS_SEG_EMPRESA
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_SEG_OFERTA:
    descripcion: Inventario tecnico de la tabla HIS_SEG_OFERTA
    destino_sugerido: MONGODB
    sensible: false
  HIS_SISBEN_OFT:
    descripcion: Inventario tecnico de la tabla HIS_SISBEN_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_SITUACION_OCUP:
    descripcion: Inventario tecnico de la tabla HIS_SITUACION_OCUP
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_SUELDO_OFERTA:
    descripcion: Inventario tecnico de la tabla HIS_SUELDO_OFERTA
    destino_sugerido: POSTGRESQL
    sensible: false
  HIS_ZONA_OFT:
    descripcion: Inventario tecnico de la tabla HIS_ZONA_OFT
    destino_sugerido: POSTGRESQL
    sensible: false
  INSCRIPCION_CURSO:
    descripcion: Inventario tecnico de la tabla INSCRIPCION_CURSO
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_DEM_ETD_FORMAL:
    descripcion: Inventario tecnico de la tabla LOG_DEM_ETD_FORMAL
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_MC_REQ_CAPTURADO:
    descripcion: Inventario tecnico de la tabla LOG_MC_REQ_CAPTURADO
    destino_sugerido: MONGODB
    sensible: true
  LOG_OFT_CUESTIONARIO:
    descripcion: Inventario tecnico de la tabla LOG_OFT_CUESTIONARIO
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_OFT_ETD_FORMAL:
    descripcion: Inventario tecnico de la tabla LOG_OFT_ETD_FORMAL
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_OFT_ETD_FORMAL_ALT:
    descripcion: Inventario tecnico de la tabla LOG_OFT_ETD_FORMAL_ALT
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_OFT_ETD_NO_FORMAL:
    descripcion: Inventario tecnico de la tabla LOG_OFT_ETD_NO_FORMAL
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_OFT_ETD_NO_FORMAL_ALT:
    descripcion: Inventario tecnico de la tabla LOG_OFT_ETD_NO_FORMAL_ALT
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_OFT_EXPERIENCIA:
    descripcion: Inventario tecnico de la tabla LOG_OFT_EXPERIENCIA
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_OFT_IDIOMA:
    descripcion: Inventario tecnico de la tabla LOG_OFT_IDIOMA
    destino_sugerido: POSTGRESQL
    sensible: false
  LOG_REQ_BANIN:
    descripcion: Inventario tecnico de la tabla LOG_REQ_BANIN
    destino_sugerido: POSTGRESQL
    sensible: true
  LOG_REQ_BANIN_BK2024:
    descripcion: Inventario tecnico de la tabla LOG_REQ_BANIN_BK2024
    destino_sugerido: MONGODB
    sensible: true
  MC_BANIN_REQ_CAPTURADO:
    descripcion: Inventario tecnico de la tabla MC_BANIN_REQ_CAPTURADO
    destino_sugerido: POSTGRESQL
    sensible: true
  MC_BANIN_REQ_CAPTURADO_BK2024:
    descripcion: Inventario tecnico de la tabla MC_BANIN_REQ_CAPTURADO_BK2024
    destino_sugerido: MONGODB
    sensible: true
  OFERTA:
    descripcion: Inventario tecnico de la tabla OFERTA
    destino_sugerido: POSTGRESQL
    sensible: true
  OFT_COMP_LABORAL:
    descripcion: Inventario tecnico de la tabla OFT_COMP_LABORAL
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_CORREO_DEM:
    descripcion: Inventario tecnico de la tabla OFT_CORREO_DEM
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_CTL_CONSULTA_DEM:
    descripcion: Inventario tecnico de la tabla OFT_CTL_CONSULTA_DEM
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_ETD_FORMAL:
    descripcion: Inventario tecnico de la tabla OFT_ETD_FORMAL
    destino_sugerido: POSTGRESQL
    sensible: true
  OFT_ETD_FORMAL_ALT:
    descripcion: Inventario tecnico de la tabla OFT_ETD_FORMAL_ALT
    destino_sugerido: POSTGRESQL
    sensible: true
  OFT_ETD_NO_FORMAL:
    descripcion: Inventario tecnico de la tabla OFT_ETD_NO_FORMAL
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_ETD_NO_FORMAL_ALT:
    descripcion: Inventario tecnico de la tabla OFT_ETD_NO_FORMAL_ALT
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_EXPERIENCIA:
    descripcion: Inventario tecnico de la tabla OFT_EXPERIENCIA
    destino_sugerido: POSTGRESQL
    sensible: true
  OFT_IDIOMA:
    descripcion: Inventario tecnico de la tabla OFT_IDIOMA
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_LICENCIA:
    descripcion: Inventario tecnico de la tabla OFT_LICENCIA
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_NOTAS_PERFIL:
    descripcion: Inventario tecnico de la tabla OFT_NOTAS_PERFIL
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_PREFERENCIA_OCUP:
    descripcion: Inventario tecnico de la tabla OFT_PREFERENCIA_OCUP
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_TALLER:
    descripcion: Inventario tecnico de la tabla OFT_TALLER
    destino_sugerido: POSTGRESQL
    sensible: false
  OFT_VEHICULO:
    descripcion: Inventario tecnico de la tabla OFT_VEHICULO
    destino_sugerido: POSTGRESQL
    sensible: false
  OFTXMBE:
    descripcion: Inventario tecnico de la tabla OFTXMBE
    destino_sugerido: POSTGRESQL
    sensible: false
  OFTXPES:
    descripcion: Inventario tecnico de la tabla OFTXPES
    destino_sugerido: POSTGRESQL
    sensible: false
  PASANTIAXFUNCION:
    descripcion: Inventario tecnico de la tabla PASANTIAXFUNCION
    destino_sugerido: POSTGRESQL
    sensible: false
  PROSP_SOCIAL_DIANA_20190328:
    descripcion: Inventario tecnico de la tabla PROSP_SOCIAL_DIANA_20190328
    destino_sugerido: MONGODB
    sensible: true
  RED_UNIDOS:
    descripcion: Inventario tecnico de la tabla RED_UNIDOS
    destino_sugerido: MONGODB
    sensible: false
  RED_UNIDOS_20201029:
    descripcion: Inventario tecnico de la tabla RED_UNIDOS_20201029
    destino_sugerido: MONGODB
    sensible: false
  RED_UNIDOS_DIANA_2018:
    descripcion: Inventario tecnico de la tabla RED_UNIDOS_DIANA_2018
    destino_sugerido: MONGODB
    sensible: false
  RED_UNIDOS_GINA_29_06_2018:
    descripcion: Inventario tecnico de la tabla RED_UNIDOS_GINA_29_06_2018
    destino_sugerido: MONGODB
    sensible: true
  REMISION_CARGUE_HIDROCARBUROS:
    descripcion: Inventario tecnico de la tabla REMISION_CARGUE_HIDROCARBUROS
    destino_sugerido: POSTGRESQL
    sensible: false
  RUV:
    descripcion: Inventario tecnico de la tabla RUV
    destino_sugerido: MONGODB
    sensible: false
  RUV_20180420:
    descripcion: Inventario tecnico de la tabla RUV_20180420
    destino_sugerido: MONGODB
    sensible: true
  RUV_20180814:
    descripcion: Inventario tecnico de la tabla RUV_20180814
    destino_sugerido: MONGODB
    sensible: true
  RUV_20181012:
    descripcion: Inventario tecnico de la tabla RUV_20181012
    destino_sugerido: MONGODB
    sensible: true
  RUV_20191017:
    descripcion: Inventario tecnico de la tabla RUV_20191017
    destino_sugerido: MONGODB
    sensible: true
  RUV_AUX:
    descripcion: Inventario tecnico de la tabla RUV_AUX
    destino_sugerido: MONGODB
    sensible: true
  SEC_USU_EVENT:
    descripcion: Inventario tecnico de la tabla SEC_USU_EVENT
    destino_sugerido: POSTGRESQL
    sensible: false
  SEC_USUARIO:
    descripcion: Inventario tecnico de la tabla SEC_USUARIO
    destino_sugerido: POSTGRESQL
    sensible: true
  SEC_USUARIO_ROL:
    descripcion: Inventario tecnico de la tabla SEC_USUARIO_ROL
    destino_sugerido: POSTGRESQL
    sensible: false
  SENA_UNIDOS:
    descripcion: Inventario tecnico de la tabla SENA_UNIDOS
    destino_sugerido: MONGODB
    sensible: true
  SYS_ARCHIVO:
    descripcion: Inventario tecnico de la tabla SYS_ARCHIVO
    destino_sugerido: POSTGRESQL
    sensible: true
  SYS_ARCHIVO_DESCARGA:
    descripcion: Inventario tecnico de la tabla SYS_ARCHIVO_DESCARGA
    destino_sugerido: POSTGRESQL
    sensible: false
  SYS_ARCHIVO_PERMISO:
    descripcion: Inventario tecnico de la tabla SYS_ARCHIVO_PERMISO
    destino_sugerido: POSTGRESQL
    sensible: false
  TEMP_DEMVACRUCE:
    descripcion: Inventario tecnico de la tabla TEMP_DEMVACRUCE
    destino_sugerido: MONGODB
    sensible: false
  TEMP_EMPLEATE:
    descripcion: Inventario tecnico de la tabla TEMP_EMPLEATE
    destino_sugerido: MONGODB
    sensible: true
  TEMP_FAMILIA_ACCION:
    descripcion: Inventario tecnico de la tabla TEMP_FAMILIA_ACCION
    destino_sugerido: MONGODB
    sensible: true
  TEMP_PROSPERID_S:
    descripcion: Inventario tecnico de la tabla TEMP_PROSPERID_S
    destino_sugerido: MONGODB
    sensible: true
  USU_CARACTERIZACION:
    descripcion: Inventario tecnico de la tabla USU_CARACTERIZACION
    destino_sugerido: POSTGRESQL
    sensible: false
  VACANTE:
    descripcion: Inventario tecnico de la tabla VACANTE
    destino_sugerido: POSTGRESQL
    sensible: false
  WS_OFERTA:
    descripcion: Inventario tecnico de la tabla WS_OFERTA
    destino_sugerido: POSTGRESQL
    sensible: true