esquema_origen: SPE
tablas:
  
  PARAMETRO:
     descripcion: Inventario tecnico de la tabla PARAMETRO
     destino_sugerido: POSTGRESQL
     sensible: true
  PARAMETROS:
     descripcion: Inventario tecnico de la tabla PARAMETROS
     destino_sugerido: POSTGRESQL
     sensible: true
